name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run SonarCloud Analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=vignesh1234-vi_WebappPort
            -Dsonar.organization=m-vignesh
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.inclusions=**
            -Dsonar.exclusions=**/*.test.js,**/*.spec.js
            -Dsonar.verbose=true
